[package]
name = "r3_support_rza1"
version = "0.2.2"
description = "Supporting package for running R3-OS on Renesas RZ/A1"
categories = ["embedded", "no-std"]
keywords = ["r3", "arm", "renesas"]

edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
semver-exempt = [
    "embedded-hal",
    "rza1/cpg",
    "rza1/gpio",
    "rza1/scif",
    "nb",
]

# Used for documentation builds [ref:doc_feature]
doc = []

[dependencies]
r3_port_arm = { version = "0.2.0", path = "../r3_port_arm" }
r3_portkit = { version = "0.2.0", path = "../r3_portkit" }
r3_kernel = { version = "0.1.0", path = "../r3_kernel" }
r3 = { version = "0.2.0", path = "../r3" }

embedded-hal = { version = "0.2.4", optional = true }
rza1 = { version = "0.2.0", features = ["ostm"] }
nb = { version = "1.0.0", optional = true }

[package.metadata.docs.rs]
all-features = true
targets = []
rustdoc-args = ["--html-in-header", "src/common.md"]  # [ref:doc_global_styling]
