[package]
name = "r3_support_rza1"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Supporting package for running R3 on Renesas RZ/A1"
categories = ["embedded", "no-std"]
keywords = ["r3", "arm", "renesas"]
repository = "https://github.com/yvt/r3"

[features]
semver-exempt = [
    "embedded-hal",
    "rza1/cpg",
    "rza1/gpio",
    "rza1/scif",
    "nb",
]

[dependencies]
r3_port_arm = { version = "0.1.0", path = "../r3_port_arm" }
r3_portkit = { version = "0.1.0", path = "../r3_portkit" }
r3 = { version = "0.1.0", path = "../r3" }

embedded-hal = { version = "0.2.4", optional = true }
rza1 = { version = "0.2.0", features = ["ostm"] }
nb = { version = "1.0.0", optional = true }

[package.metadata.docs.rs]
targets = []
