[package]
name = "r3_support_rp2040"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Supporting package for running R3 on RP2040"
categories = ["embedded", "no-std"]
keywords = ["r3", "arm"]
repository = "https://github.com/yvt/r3"

[features]
semver-exempt = [
    "embedded-hal",
    "usbd-serial",
    "inline_dyn",
    "usb-device",
    "cortex-m",
    "vcell",
    "nb",
]

[dependencies]
r3_port_arm_m = { version = "0.1.0", path = "../r3_port_arm_m" }
r3_portkit = { version = "0.1.0", path = "../r3_portkit" }
r3 = { version = "0.1.0", path = "../r3" }

embedded-hal = { version = "0.2.4", optional = true }
usbd-serial = { version = "0.1.1", optional = true }
inline_dyn = { version = "0.1.1", optional = true }
usb-device = { version = "0.2.7", optional = true }
cortex-m = { version = "0.6.3", optional = true, features = ["inline-asm"] }
rp2040 = { version = "0.1.0" }
vcell = { version = "0.1.2", optional = true }
nb = { version = "1.0.0", optional = true }

[package.metadata.docs.rs]
targets = []
