[package]
name = "constance_test_suite"
version = "0.0.1"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
default = ["tests_all"]
tests_all = []
tests_selective = []

[dependencies]
constance = { path = "../constance" }
log = "0.4.8"
wyhash = "0.3.0"
