[package]
name = "constance_test_suite"
version = "0.0.1"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT OR Apache-2.0"
categories = ["embedded", "no-std", "development-tools::testing"]
description = "Test suite for Constance"
keywords = ["constance"]
repository = "https://github.com/yvt/Constance"

[features]
default = ["tests_all"]
tests_all = []
tests_selective = []

[dependencies]
constance = { path = "../constance" }
wyhash = "0.3.0"
log = "0.4.8"

[dev-dependencies]
env_logger = "0.7.1"
