[workspace]
members = [
    "examples/basic",
    "examples/basic_nucleo_f401re",
    "src/constance",
    "src/constance_parse_generics",
    "src/constance_port_arm_m",
    "src/constance_port_std",
    "src/constance_test_suite",
]
