[workspace]
members = [
    "examples/basic",
    "examples/basic_gr_peach",
    "examples/basic_nucleo_f401re",
    "examples/basic_rp_pico",
    "examples/smp_rp_pico",
    "src/arm_semihosting",
    "src/r3",
    "src/r3_port_arm",
    "src/r3_port_arm_m",
    "src/r3_port_arm_m_test_driver",
    "src/r3_port_arm_test_driver",
    "src/r3_port_riscv",
    "src/r3_port_riscv_test_driver",
    "src/r3_port_std",
    "src/r3_portkit",
    "src/r3_support_rp2040",
    "src/r3_support_rza1",
    "src/r3_test_runner",
    "src/r3_test_suite",
]

[patch.crates-io.probe-rs]
# Chose a commit from the narrow window in which `probe-rs` isn't affected by
# <https://github.com/probe-rs/probe-rs/issues/352> and at the same time
# includes <https://github.com/probe-rs/probe-rs/pull/311> (the fix for another
# issue that affects us).
git = "https://github.com/probe-rs/probe-rs.git"
rev = "8bb53577ccee46550c0b688dfc2d13c1cd896083"

[profile.release]
debug = true
lto = true
