[package]
name = "r3_test_runner"
version = "0.0.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
r3_test_suite = { path = "../r3_test_suite", default-features = false }

arg_enum_proc_macro = "0.3.0"
aho-corasick = "0.7.13"
futures-core = "0.3.5"
probe-rs-rtt = "0.3.0"
tokio-serial = "4.3.3"
lazy_static = "1.4.0"
env_logger = "0.7.1"
mio-serial = "3.3.1"
serde_json = "1.0.57"
itertools = "0.9.0"
structopt = "0.3.15"
thiserror = "1.0.20"
probe-rs = "0.8.0"
tempdir = "0.3.7"
anyhow = "1.0.32"
serde = "1.0.114"
toml = "0.5.6"
log = "0.4.8"
crc = "1.8.1"

[dependencies.goblin]
version = "0.2.3"
default-features = false
features = ["std", "elf32"]

[dependencies.tokio]
version = "0.2.21"
features = ["process", "macros", "time", "io-util", "io-std", "fs", "blocking", "sync"]
