[package]
name = "r3_test_runner"
version = "0.0.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
r3_test_suite = { path = "../r3_test_suite", default-features = false }

arg_enum_proc_macro = "0.3.0"
aho-corasick = "0.7.13"
futures-core = "0.3.5"
probe-rs-rtt = "0.11.0"
tokio-serial = "5.4.1"
lazy_static = "1.4.0"
env_logger = "0.8.4"
serde_json = "1.0.57"
serialport = "4.0.0"
itertools = "0.10.0"
pin-utils = "0.1.0"
structopt = "0.3.15"
thiserror = "1.0.20"
probe-rs = "0.11.0"
tempdir = "0.3.7"
anyhow = "1.0.32"
serde = "1.0.114"
rusb = "0.8"
toml = "0.5.6"
log = "0.4.8"
crc = "2.0.0"

[dependencies.goblin]
version = "0.4.3"
default-features = false
# FIXME: <https://github.com/m4b/goblin/issues/212> `elf64` isn't actually used
features = ["std", "elf32", "elf64", "endian_fd"]

[dependencies.tokio]
version = "1"
features = ["process", "macros", "time", "io-util", "io-std", "fs", "sync", "rt"]
