[package]
name = "r3_test_suite"
version = "0.0.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT OR Apache-2.0"
categories = ["embedded", "no-std", "development-tools::testing"]
description = "Test suite for R3"
keywords = ["r3"]
repository = "https://github.com/yvt/r3"
publish = false

[features]
default = ["tests_all", "full"]
tests_all = []
tests_selective = []

# The kernel's optional features
full = [
    "priority_boost",
    "system_time",
]
priority_boost = ["r3/priority_boost"]
system_time = ["r3/system_time"]

[dependencies]
r3 = { version = "0.1.0", path = "../r3" }

assert_matches = { version = "1.4.0" }
arrayvec = { version = "0.7.1", default-features = false }
wyhash = { version = "0.5.0" }
log = { version = "0.4.8" }

[dev-dependencies]
quickcheck_macros = "0.9.1"
env_logger = "0.7.1"
quickcheck = "0.9.2"

[package.metadata.docs.rs]
targets = []
