[package]
name = "r3_test_suite"
version = "0.0.0"
categories = ["embedded", "no-std", "development-tools::testing"]
description = "Test suite for R3"
keywords = ["r3"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["tests_all", "full"]
tests_all = []
tests_selective = []

# The kernel features to be used by the test suite. E.g., if `system_time` is
# set, the tests will require `System: raw::KernelTime` and use it to introduce
# additional assertions.
full = [
    "priority_boost",
    "system_time",
]
priority_boost = []
system_time = []

[dependencies]
r3 = { workspace = true, features = ["sync"] }

assert_matches = { version = "1.4.0" }
arrayvec = { version = "0.7.1", default-features = false }
wyhash = { version = "0.5.0" }
log = { version = "0.4.8" }

[dev-dependencies]
quickcheck_macros = "1.0.0"
env_logger = "0.8.4"
quickcheck = "1.0.3"

[package.metadata.docs.rs]
targets = []
