[package]
name = "basic_gr_peach"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
constance = { path = "../../src/constance" }

rtt-target = { version = "0.2.0" }
register = "0.5.1"
r0 = "0.2.2"