[target.thumbv7m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[target.thumbv7em-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
