[package]
name = "r3_portkit"
version = "0.1.2"
authors = ["yvt <i@yvt.jp>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utilities for writing a port of R3"
keywords = ["r3", "simulator"]
repository = "https://github.com/r3-os/r3"

[features]
doc = ["svgbobdoc/enable"]

[dependencies]
r3 = { version = "0.1.1", path = "../r3" }

num-rational = { version = "0.4.0", default-features = false }
svgbobdoc = { version = "0.3.0-alpha.1" }

[dev-dependencies]
quickcheck_macros = { version = "1.0.0" }
num-integer = { version = "0.1.43", default-features = false }
env_logger = { version = "0.8.4" }
quickcheck = { version = "1.0.3" }
itertools = { version = "0.10.0" }
log = { version = "0.4.8" }

[package.metadata.docs.rs]
all-features = true
targets = []
