[package]
name = "r3_portkit"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Utilities for writing a port of R3"
categories = ["embedded", "no-std"]
keywords = ["r3", "simulator"]
repository = "https://github.com/r3-os/r3"

[features]
# Used for documentation builds [ref:doc_feature]
doc = ["svgbobdoc/enable"]

[dependencies]
r3_kernel = { version = "0.1.0", path = "../r3_kernel" }
r3_core = { version = "0.1.0", path = "../r3_core" }

num-rational = { version = "0.4.0", default-features = false }
svgbobdoc = { version = "0.3.0-alpha.4" }

[dev-dependencies]
quickcheck_macros = { version = "1.0.0" }
num-integer = { version = "0.1.43", default-features = false }
env_logger = { version = "0.8.4" }
quickcheck = { version = "1.0.3" }
itertools = { version = "0.10.0" }
log = { version = "0.4.8" }

[package.metadata.docs.rs]
all-features = true
targets = []
rustdoc-args = ["--html-in-header", "src/common.md"]  # [ref:doc_global_styling]
