[package]
name = "r3_port_riscv"
version = "0.1.3"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "RISC-V port for R3"
categories = ["embedded", "no-std"]
keywords = ["r3", "riscv"]
repository = "https://github.com/r3-os/r3"

[features]
emulate-lr-sc = []
maintain-pie = []
preload-registers = []

# Enable the diagram rendering by svgbob
doc = ["svgbobdoc/enable"]

[dependencies]
r3_portkit = { version = "0.1.1", path = "../r3_portkit" }
r3_kernel = { version = "0.0.0", path = "../r3_kernel" }
r3_core = { version = "0.1.0", path = "../r3_core" }

tock-registers = { version = "0.7.0" }
svgbobdoc = { version = "0.3.0-alpha.4" }
riscv-rt = { version = ">= 0.6.0, < 0.9.0" }
riscv = { version = ">= 0.5.0, < 0.8.0" }

[package.metadata.docs.rs]
targets = []
