[package]
name = "constance_port_std"
version = "0.0.1"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
atomic_ref = { version = "0.1", features = ["nightly"] }
constance = { path = "../constance" }
log = "0.4.8"
env_logger = "0.7.1"
parking_lot = "0.10.2"

[dev-dependencies]
constance_test_suite = { path = "../constance_test_suite" }

[target."cfg(unix)".dependencies]
libc = "0.2.71"
errno = "0.2.5"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3.8", features = ["processthreadsapi"] }

