[package]
name = "r3_port_std"
version = "0.1.2"
authors = ["yvt <i@yvt.jp>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Simulation environment for running R3 on a hosted environment"
keywords = ["r3", "simulator"]
repository = "https://github.com/yvt/r3"

[dependencies]
r3 = { version = "0.1.1", path = "../r3" }

atomic_ref = { version = "0.2.0" }
env_logger = { version = "0.8.4" }
once_cell = { version = "1.4.0" }
spin = { version = "0.9.2", default-features = false, features = ["spin_mutex"] }
slab = { version = "0.4.5" }
log = { version = "0.4.8" }

[dev-dependencies.r3_test_suite]
path = "../r3_test_suite"
default-features = false
features = ["tests_all"]

[target."cfg(unix)".dependencies]
libc = "0.2.71"
errno = "0.2.5"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3.8", features = ["processthreadsapi"] }

[[bench]]
name = "test_suite"
harness = false

[package.metadata.docs.rs]
targets = []
