[package]
name = "constance"
version = "0.0.1"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "../../README.md"
description = "Static RTOS testing the limit of Rust's const eval and generics"
categories = ["embedded", "no-std"]
keywords = ["constance", "rtos"]
repository = "https://github.com/yvt/Constance"

[dependencies]
tokenlock = { version = "0.3.0", default-features = false }
atomic_ref = { version = "0.1", features = ["nightly"] }
num-integer = "0.1.42"
num-traits = "0.2.11"
bitflags = "1.2.1"
parse-generics-shim = { version = "0.1.1" }
svgbobdoc = "0.2.2"
staticvec = { version = "0.10.1", default-features = false }
pin-utils = "0.1.0"
chrono = { version = "0.4.13", optional = true, default-features = false }

[dev-dependencies]
env_logger = "0.7.1"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
log = "0.4.8"
