[package]
name = "constance"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenlock = { version = "0.3.0", default-features = false }
atomic_ref = { version = "0.1", features = ["nightly"] }
num-integer = "0.1.42"
