[package]
name = "constance"
version = "0.0.1"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenlock = { version = "0.3.0", default-features = false }
atomic_ref = { version = "0.1", features = ["nightly"] }
num-integer = "0.1.42"
num-traits = "0.2.11"
bitflags = "1.2.1"
parse-generics-shim = { version = "0.1.1" }
svgbobdoc = "0.2.2"

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
log = "0.4.8"
