[package]
name = "constance_example_basic"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
publish = false

[dependencies]
constance_port_std = { path = "../../src/constance_port_std" }
constance = { path = "../../src/constance" }

log = { version = "0.4.8" }
