[package]
name = "r3_example_basic"
version = "0.0.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
publish = false

[dependencies]
r3_port_std = { path = "../../src/r3_port_std" }
r3 = { path = "../../src/r3", features = ["system_time"] }

log = { version = "0.4.8" }
