name: Docs
on:
  push:
    branches: [🦆]

jobs:
  check:
    name: Build and Deploy Docs
    runs-on: ubuntu-20.04
    # FIXME: This workflow is temporarily disabled until the following issue
    #        is fixed: <https://github.com/rust-lang/rust/issues/82284>
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Build Documentation for “r3_port_std”
        uses: actions-rs/cargo@v1
        with: { command: doc, args: -p r3_port_std }

      - name: Build Documentation for “r3_port_arm”
        uses: actions-rs/cargo@v1
        with: { command: doc, args: -p r3_port_arm }

      - name: Build Documentation for “r3_port_arm_m”
        uses: actions-rs/cargo@v1
        with: { command: doc, args: -p r3_port_arm_m }

      - name: Build Documentation for “r3_port_riscv”
        uses: actions-rs/cargo@v1
        with: { command: doc, args: -p r3_port_riscv }

      - name: Build Documentation for “r3_support_rp2040”
        uses: actions-rs/cargo@v1
        with: { command: doc, args: -p r3_support_rp2040 }

      - name: Build Documentation for “r3_support_rza1”
        uses: actions-rs/cargo@v1
        with: { command: doc, args: -p r3_support_rza1 }

      - name: Build Documentation for “r3”
        uses: actions-rs/cargo@v1
        with: { command: doc, args: -p r3 --all-features }

      - name: Generate Badge
        run: |
          rev=`git show-ref --head HEAD | cut -b 1-7`
          wget -nv -O target/doc/badge.svg "https://img.shields.io/badge/docs-$rev-ok?style=for-the-badge"

      - name: Collect Output
        run: |
          mkdir output
          mv target/doc output

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
